version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Nothing to do.
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo $CODEBUILD_SOURCE_VERSION
      - PULL_REQUEST=true
      - echo $CODEBUILD_SOURCE_VERSION | grep -q "pr" || PULL_REQUEST=false
  build:
    commands:
      - echo Entered the build phase on `date`...
      - echo Building the site.
      - if $PULL_REQUEST; then
          echo Repo not deployed becasue this is a Pull Request.;
        else
          npm run build;
        fi
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Nothing to do.
      - echo Build completed on `date`.